// Generated by scripts/fetch-outlet-logos.mjs — do not edit by hand.
// Maps articles.source to a bundled icon in public/outlets/.
export const OUTLET_LOGO_FILES: Record<string, string> = {
  "Detik": "/outlets/detik.ico",
  "detikcom": "/outlets/detikcom.ico",
  "Kompas": "/outlets/kompas.ico",
  "Antara": "/outlets/antara.png",
  "Tempo": "/outlets/tempo.webp",
  "CNN Indonesia": "/outlets/cnn-indonesia.png",
  "Republika": "/outlets/republika.png",
  "Al Jazeera": "/outlets/al-jazeera.ico",
  "The Guardian": "/outlets/the-guardian.png",
  "BBC News": "/outlets/bbc-news.png",
  "CNBC": "/outlets/cnbc.png",
  "Bisnis": "/outlets/bisnis.ico",
  "Kontan": "/outlets/kontan.ico"
};
